# SQL Interview Questions  - Quiz


## Introduction

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

What are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

There are actually 5 main datatypes in SQLite3:
* Null: The value is a NULL value
* Integer: The value is a signed integer stored in 1, 2, 3, 4, 6, or 8 bytes depending on magnitude of the value
* Real: The value is a floating point value, stored as an 8-byte IEEE floating point number
* Text: The value is a text string
* Blob: The value is a blob of data, stored exactly as it was input.

Yes ex. boolean, date & time datatype. 

---

## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Foreign Key - a column or a set of columns in one table that references the *primary key* columns in another table.

Primary Key - a column or set of collumns where each value is unique and identifies a single row of the table. 

* Ex. An address if the rows in the table were mailboxes then the primary key would be the street address. Each unique. There cannot be any blank or NULL values present.

---

## Question 3

Explain the different types of relationships entities can have in a SQL database. 

There are three types of relationships:
1. One to One Relationship: Each record in Table A relates to one, and only one, record in Table B. Each record in Table B relates to one and only one record in Table A. Ex. Only sharing the column of EmployeeID.

2. One to Many Relationship: A record in Table A can relate to zero, one, or many records in Table B. Many records in Table B can relate to one record in Table A. Ex. Customer and orders table. There could be many orders for one customer or no orders at all. 

3. Many to Many Relationship: Two tables holding data about employees and the projects to which they are assigned. Each project can involve more than one employee and each employee can be working on more than one project. 


## Question 4

Explain the various types of JOINs possible with SQL. 

* Inner Join: Returns records that have matching values in both tables.
* Left (Outer) Join: Returns all records from the left table and the matched records from the right table
* Right (Outer) Join: Returns all records form the right table and the matched records from the left table. 
* Full (Outer) Join: Returns all records where there is a match in either left or right table. 



## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

GROUP BY is usually used along with 5 built in aggregate functions. 
* SUM(col name): total of the values in a numeric column
* AVG(col name): Average of the values in a column
* MAX(col name): Largest value in a column
* MIN(col name): Smallest value in a column
* COUNT(--): Count of the number of rows selected.


## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?

The associative table maps two or more tables together by referencing the primary keys of each data table. It contains a number of foreign keys, each in a many-to-one relationship from the junction table to the individual tables. 


## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.